CHAVE_SERPER = "902a25118f1f65d63bef8f294d747d3624642da1"
CHAVE_GEMINI = "AIzaSyCu-NlzfRDT5R4mnBK23pAHOD_RB9daWdI"
WEBHOOK_PLANILHA = "https://script.google.com/macros/s/AKfycbzR66Auf9Wl91Nw_dERjuLyemQF-CQMVGAMqcZy1plwnSGCZW8-TfaxGi2E9XopUd1b/exec"